language: node_js
node_js: 13.12.0
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.72.0/hugo_extended_0.72.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf public
    - npm install

branches:
    only:
        - hugo

script:
    - npm run build
    - dir

after_success:
    - git config --global user.name "FFRaycoder"
    - git config --global user.email "nn_201312@163.com"
    - git clone https://${GH_TOKEN}@github.com/FFRaycoder/blog-built.git container
    - git clone https://${GH_TOKEN}@github.com/FFRaycoder/ffraycoder.github.io.git f
    - rm -rf container/*
    - rm -rf f/*
    - cp -r public/* container
    - cp -r public/* f
    - cd container
    - git add -A
    - curl -H 'Content-Type:text/plain' --data-binary @baiduurls.txt "http://data.zz.baidu.com/urls?site=https://raycoder.me&token=${BAIDU_PUSH_TOKEN}"
    - git commit -m 'Travis update blog'
    - git push -u origin master -f
    - cd f
    - git add -A
    - git commit -m 'Travis update blog'
    - git push -u origin master -f